# This CI fails, because it looks Azure Pipelines doesn't support Alpine OS container.

resources:
  containers:
  - container: alpine
    image: nginx:alpine
    # image: matoba/node10-puppeteer:azure-pipe

pool:
  vmImage: 'Ubuntu 16.04'

container: alpine

steps:
- script: |
    ls
  displayName: 'foo'