pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    docker -v
    docker version -f '{{.Server.Experimental}}'
    docker-compose -v
    docker login -u $(dockerId) -p $(dockerPw)
  displayName: 'prepare'
- script: |
    docker pull nginx:alpine
    docker tag nginx:alpine matoba/nginx
  displayName: 'build'
- script: |
    docker-compose build
    docker-compose up -d
  displayName: 'run'
- script: |
    curl https://127.0.0.1/
  displayName: 'test'
- script: |
    docker push matoba/nginx
  displayName: 'push'
