
jobs:
- job: prepare
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      docker -v
      docker-compose -v
      docker login -u $(dockerId) -p $(dockerPw)
    displayName: 'prepare'

- job: run
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      docker pull nginx:alpine
      docker tag nginx:alpine matoba/nginx
    displayName: 'build'
  - script: |
      docker run -d -p 80:80 matoba/nginx
    displayName: 'run'
  - script: |
      curl http://127.0.0.1/
    displayName: 'test'
  - script: |
      docker push matoba/nginx
    displayName: 'push'
