# This CI fails, because it looks Azure Pipelines doesn't support Alpine OS container.

resources:
  containers:
  - container: deb
    image: nginx:alpine
    # image: matoba/node10-puppeteer:azure-pipe

pool:
  vmImage: 'ubuntu-16.04'

container: deb

steps:
- script: ls
  displayName: 'foo'
