pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    docker -v
    docker-compose -v
  displayName: 'check docker'
- script: |
    docker run -d -p 80:80 nginx:alpine
  displayName: 'run container'
- script: |
    curl http://127.0.0.1/
  displayName: 'test'
